prompt --application/pages/page_00006
begin
--   Manifest
--     PAGE: 00006
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000008
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_page.create_page(
 p_id=>6
,p_name=>'APP'
,p_alias=>'APPROVALS1'
,p_step_title=>'Approvals'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/** Products JS */',
'/**',
' * Dynamic Product Table with Pagination',
' * -------------------------------------',
' */',
'let pendingData = [];',
'let approvedData = [];',
'let deniedData = [];',
'let currentPage = 1;',
'// Data Fetchers',
'const getData = (offset, process, type) => {',
'  apex.server.process(process, {',
'    x01: $v(''P9_COMPANY_ID''),',
'    x02: offset',
'  }, {',
'    dataType: "json",',
'    success: function(data) {',
'        if(type === ''pending''){',
'            pendingData = [...data];  ',
'            renderPendingTablePage(offset);',
'        }',
'        if(type === ''approved''){',
'            approvedData = [...data];',
'            renderApprovedTablePage(offset);',
'        }',
'        if(type === ''denied''){',
'            deniedData = [...data];',
'            renderDeniedTablePage(offset);',
'            console.log(deniedData);',
'        }',
'    },',
'    error: function(jqXHR, textStatus, errorThrown) {',
'      console.error("Error loading product data:", textStatus, errorThrown);',
'    }',
'  });',
'  return false;',
'};',
'',
'function changeSelect(value) {',
'    console.log(document.getElementById(''page-select'').value);',
'  document.getElementById(''page-select'').value = value;',
'  // Trigger the onchange event manually if needed',
'  document.getElementById(''page-select'').dispatchEvent(new Event(''change''));',
'}',
'',
'// Pagination Handler',
'function apprPaginate(direction, process, item, type, totalCount) {',
'  let current = parseInt($v(item)) || 0;',
'  //const pageSize = 1;',
'  let newOffset = current + (direction);',
'  if (newOffset < 1) newOffset = 1;',
'  if (newOffset > totalCount) newOffset = totalCount;',
'  $s(item, newOffset);',
'  getData(newOffset, process, type);',
'  changeSelect(newOffset)',
'  return false;',
'}',
'',
'function handlePageChange(selectElement, process, item, type) {',
'  const selectedValue = parseInt(selectElement.value);',
'  console.log("Selected page:", selectedValue);',
'  $s(item, selectedValue);',
'  getData(selectedValue, process, type);',
'  return false;',
'}',
'',
'// Table Rendering Functions',
'const pendingTableBody = document.getElementById("pending-table-body");',
'const approvedTableBody = document.getElementById("approved-table-body");',
'const deniedTableBody = document.getElementById("denied-table-body");',
'',
'function renderPendingTablePage(page) {',
'  pendingTableBody.innerHTML = "";',
'  ',
'    const rowsPerPage = 5;',
'    const start = (page - 1) * rowsPerPage;',
'    const end = start + rowsPerPage;',
'    const pageData = pendingData.slice(start, end);',
'',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    row.innerHTML = `',
'      <td>${item.personId}</td>',
'      <td>${item.fullName}</td>',
'      <td>${item.loanType}</td>',
'      <td style="font-weight:700;color:#2C2E2F;">${item.loanAmount}</td>',
'      <td><span class="status ${item.status.toLowerCase()}">${item.status}</span></td>',
unistr('      <td><a href="#" onclick="return redirectToModalPageUpdateProduct(10, ${item.productId}, ${item.loanId})">Take Action \270E</a></td>'),
'    `;',
'    pendingTableBody.appendChild(row);',
'  });',
'}',
'',
'function renderApprovedTablePage(page) {',
'  approvedTableBody.innerHTML = "";',
'  ',
'    const rowsPerPage = 5;',
'    const start = (page - 1) * rowsPerPage;',
'    const end = start + rowsPerPage;',
'    const pageData = approvedData.slice(start, end);',
'	',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    if(item.approvalLevel == 5){',
'        row.innerHTML = `',
'        <td>${item.personId}</td>',
'        <td>${item.fullName }</td>',
'        <td>${item.loanType }</td>',
unistr('        <td style="font-weight:700;color:#2C2E2F;">\20A6${item.loanAmount}</td>'),
'        <td><span class="status ${item.disbursedStatus}">${item.disbursedStatus}</span></td>',
'        <td>${item.disbursedDate}</td>',
'        `;',
'    }else{',
'          row.innerHTML = `',
'            <td>${item.personId}</td>',
'            <td>${item.fullName }</td>',
'            <td>${item.loanType }</td>',
unistr('            <td style="font-weight:700;color:#2C2E2F;">\20A6${item.loanAmount}</td>'),
'            <td><span class="status ${item.status}">${item.status}</span></td>',
'            <td>${item.approvalDate}</td>',
'    `;',
'    }',
'    approvedTableBody.appendChild(row);',
'  });',
'}',
'',
'',
'function renderDeniedTablePage(page) {',
'  deniedTableBody.innerHTML = "";',
'  ',
'    const rowsPerPage = 5;',
'    const start = (page - 1) * rowsPerPage;',
'    const end = start + rowsPerPage;',
'    const pageData = deniedData.slice(start, end);',
'	',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    if(item.approvalLevel == 5){',
'        row.innerHTML = `',
'        <td>${item.personId}</td>',
'        <td>${item.fullName }</td>',
'        <td>${item.loanType }</td>',
unistr('        <td style="font-weight:700;color:#2C2E2F;">\20A6${item.loanAmount}</td>'),
'        <td><span class="status ${item.disbursedStatus}">${item.disbursedStatus}</span></td>',
'        <td>${item.disbursedDate}</td>',
'        `;',
'    }else{',
'        row.innerHTML = `',
'        <td>${item.personId}</td>',
'        <td>${item.fullName }</td>',
'        <td>${item.loanType }</td>',
unistr('        <td style="font-weight:700;color:#2C2E2F;">\20A6${item.loanAmount}</td>'),
'        <td><span class="status ${item.deniedStatus}">${item.deniedStatus}</span></td>',
'        <td>${item.deniedDate}</td>',
'        `;',
'    }',
'    deniedTableBody.appendChild(row);',
'  });',
'}',
'',
'//Modal Redirect Helpers',
'//const modal = document.getElementById(''main-modal'');',
'',
'function afterLoad() {',
'  apex.message.showPageSuccess(''success'');',
'}',
'',
'var modal = document.getElementById(''main-modal'');',
'',
'',
'function afterLoad(){',
'    apex.message.showPageSuccess(''success'');',
'}',
'',
'const redirectToModalPageUpdateProduct = (pageID,productId,loanId) => {',
'    console.log(loanId);',
'        var url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P10_PRODUCT_ID,P10_LOAN_ID,P10_HEADER:${productId},${loanId},Approve Loan`; //''f?p='' || l_app || '':''||apex_application.g_x01||'':''||l_session||''::NO::''||l_item_name||'':''||apex_applic'
||'ation.g_x02,',
'        //var url = "f?p=#APP_ID#:"+''201''+":#SESSION#::NO:RP,201:";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'        ',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'',
'                apex.navigation.redirect(pData.url);',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'',
'const redirectFunc = (action, status) => {',
'        $s(''P30_ACTION'', action);',
'        $s(''P30_STATUS'', status);',
'        var x = ''Y'';',
'        var url = "f?p=#APP_ID#:"+''26''+":#SESSION#::NO:RP,26:P26_CONFIRMED:#PARA1#";',
'        url = url.replace("#APP_ID#",&APP_ID.);',
'',
'        url = url.replace("#SESSION#", &SESSION.);',
'',
'        url = url.replace("#PARA1#", x);',
'',
'        apex.server.process("PREPARE_URL", {',
'',
'                    x01: url',
'',
'        }, {',
'',
'        success: function(pData) {',
'',
'        if (pData.success === true) {',
'                // null;',
'             //  apex.navigation.redirect(pData.url);',
'              apex.navigation.dialog.close( true, ["P30_ACTION","P30_STATUS", "P30_PRODUCT_ID"] );',
'',
'        } else {',
'',
'                console.log("FALSE");',
'',
'        }',
'',
'        },',
'',
'        error: function(request, status, error) {',
'',
unistr('               console.log("status\2014" + status + " error\2014-" + error);'),
'',
'        }',
'',
'    });',
'    ',
'    ',
'            return false;',
'        ',
'};',
'',
'',
'function open_dialog(){',
' $(''#confirm-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function openDeactivateDialog(){',
' $(''#deactivate-action'').dialog(''open''); //calling region id here to open',
'    return false;',
'}',
'',
'function closeMainModal(){',
'    $(''#modalwindow'').modal(''hide'');',
'    //  javascript:apex.navigation.dialog.close(true);',
'    return false;',
'}',
'',
'function closeModal(){',
'    apex.navigation.dialog.close(true);',
'    return false;',
'}',
'function closeInlineModal(){',
'     $(''#confirm-action'').dialog(''close''); ',
'     $(''#deactivate-action'').dialog(''close''); ',
'    return false;',
'}',
'',
'',
'function completeAction(action, id){',
'    let product_id = $v(''P30_PRODUCT_ID'');',
'    if(action == 1){ // 1 means activate',
'      apex.server.process("COMPLETE_ACTION", {',
'        x01:  ''A'',',
'        x02:  product_id,',
'      }, {',
'',
'        dataType: ''text'',',
'        success: function(pData) {',
'            if(pData == 1){ // 1 means successful',
'                redirectFunc(''activate'', ''S''); // activate and successful',
'            }else{ ',
'                redirectFunc(''activate'', ''F''); //activate and failed',
'            }',
'        }',
'      });',
'    }else{',
'        apex.server.process("COMPLETE_ACTION", {',
'            x01:  ''I'',',
'            x02:  product_id,',
'          }, {',
'',
'            dataType: ''text'',',
'            success: function(pData) {',
'                if(pData == 1){ // 1 means successful',
'                   redirectFunc(''deactivate'', ''S''); // activate and successful',
'                }else{ ',
'                   redirectFunc(''deactivate'', ''F''); //activate and failed',
'                }',
'            }',
'          });',
'    }',
'    return false;',
'}',
'',
'',
'//Filter Functions',
'function filterPending() {',
'  const input = document.getElementById(''pending-approvals-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#pending-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'function filterApproved() {',
'  const input = document.getElementById(''approved-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#approved-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'',
'function filterDenied() {',
'  const input = document.getElementById(''denied-approvals-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#denied-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'',
'window.onload = () => {',
'  getData(1, ''GET_PENDING_DATA'', ''pending'');',
'  getData(1, ''GET_APPROVED_DATA'', ''approved'');',
'  getData(1, ''GET_DENIED_DATA'', ''denied'');',
'',
'  renderPendingTablePage(currentPage);',
'  renderApprovedTablePage(currentPage);',
'  renderDeniedTablePage(currentPage);',
'};',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.table-wrapper {',
'  overflow-x: auto;',
'  /* padding: 0 8px; */',
'  width: 100%;',
'}',
'',
'.no-spinner .u-Processing {',
'    display: none !important;',
'}',
'',
'',
'/*Back Button*/',
'.icon-button {',
'  display: flex;',
'  align-items: center; /* Vertically center the icon and text */',
'  /* padding: 20px 0px; */',
'  background: #FFFFFF;',
'  color: #000000;',
'  border: none;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  font-size: 16px;',
'  transition: background-color 0.3s;',
'  margin: 8px 0;',
'}',
'',
'a{',
'    color: #7A7A7A;',
'}',
'',
'.icon {',
'  width: 20px; /* Set the width of the icon */',
'  height: 20px; /* Set the height of the icon */',
'  margin-right: 10px; /* Space between icon and text */',
'}',
'',
'',
'.button-text {',
'  white-space: nowrap; /* Prevent the text from breaking onto a new line */',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 18.4px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'}',
'',
'',
'/*Company image and name*/',
'.internal-flex{',
'  display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  margin: 20px 0;',
'}',
'',
'.img-div{',
'    padding: 4px;',
'    width: 48px;         /* Set the width of the div */',
'    height: 48px;       /* Set the height of the div */',
'    overflow: hidden; ',
'    margin-right:16px;',
'    border-radius: 4px;',
'    opacity: 0px;',
'    border: 1px solid #DDDDDD;',
'    position: relative;',
'}',
'',
'.prod-img{',
'   width: 100%;         /* Ensures the image width is 100% of the div */',
'    height: 100%;        /* Ensures the image height is 100% of the div */',
'    object-fit: cover;   /* The image will cover the div while maintaining its aspect ratio */',
'     max-width: 100%;  /* Image will never exceed the width of its container */',
'     box-sizing: border-box; /* Ensures padding is taken into account */',
'}',
'',
'.text-set p{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 20px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'/**Tabs styling**/',
'.t-Tabs{',
'    border-bottom: 1px solid #E5E5E5;',
'}',
'',
'.t-Body .t-Tabs--simple .t-Tabs-link{',
'        color:#7A7A7A;',
'        text-decoration: none;',
'    border-top: 1px solid #ddd;',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'text-align: center;',
'}',
'',
'/** Company Description **/',
'.description-header{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none; ',
'    width: Fill (531px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 0px 0px 0px;',
'    gap: 8px;',
'    border-radius: 4px 0px 0px 0px;',
'    opacity: 0px;',
'    color: #423B3B;',
'}',
'',
'/**Edit Button **/',
'',
'.edit-button {',
'  display: inline-flex;',
'  align-items: center;',
'  padding: 16px 16px 16px 0px;',
'  background-color: white;',
'  margin: 20px 0px 5px 0px;',
'  color: #1e90ff;',
'  border: none;',
'  font-size: 14px;',
'  font-weight: 500;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  transition: 0.3s;',
'}',
'',
'.edit-button .icon {',
'  width: 16px;',
'  height: 16px;',
'  margin-right: 6px;',
'  filter: invert(37%) sepia(95%) saturate(1354%) hue-rotate(189deg) brightness(95%) contrast(101%);',
'}',
'',
'/*.edit-button:hover {',
'  background-color: #e6f3ff;',
'}*/',
'',
'',
'/*Products table css*/',
'',
'.controls {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 10px;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin: 12px 0;',
'}',
'',
'.controls h2{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 18px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #32373B;',
'}',
'',
'.sort-btn{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.add-btn {',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  background: #348BEF;',
'}',
'',
'.sort-btn {',
'  background-color: #f2f2f2;',
'}',
'',
'.add-btn {',
'  background-color: #007bff;',
'  color: #fff;',
'}',
'',
'.table-wrapper {',
'  overflow-x: auto;',
'}',
'',
'table {',
'  width: 100%;',
'  border-collapse: collapse;',
'  margin-bottom: 20px;',
'  min-width: 800px;',
'}',
'',
'thead {',
'  background-color:#2C2E2F;',
'  color: white;',
'}',
'',
'th{',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #F6F7F9;',
'}',
'',
'td {',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #7A7A7A; ',
'}',
'',
'.status {',
'  padding: 4px 10px;',
'  border-radius: 10px;',
'  font-size: 0.9em;',
'  display: inline-block;',
'}',
'',
'.status.active {',
'  background-color: #d4f8d4;',
'  color: #2d7f2d;',
'}',
'',
'.status.inactive {',
'  background-color: #f8d4d4;',
'  color: #a94442;',
'}',
'',
'.status.enabled {',
'  background-color: #d4f8d4;',
'  color: #2d7f2d;',
'}',
'',
'.status.disabled {',
'  background-color: #f8d4d4;',
'  color: #a94442;',
'}',
'',
'.status.initiated {',
'   background-color: #fcfae0;',
'   color:#dea002;',
'}',
'',
'.status.Pending {',
'  background-color:  #F3E5F5 ;',
'  color: #9e16b6;',
'}',
'.status.Approved {',
'  background-color: #F0FBEE;',
'  color: #3DB22A;',
'}',
'',
'.status.Denied {',
'  background-color: #FCEEEE;',
'  color: #E05453;',
'}',
'',
'.pagination {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 10px;',
'  align-items: center;',
'  justify-content: space-between;',
'  padding: 20px 0;',
'}',
'',
'.pagination select {',
'  padding: 5px;',
'  width: 81;',
'height: 40;',
'left: 91px;',
'opacity: 0.4;',
'border-radius: 6px;',
'font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #0C0C0C;',
'}',
'',
'.pagination span{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'/* color: #0C0C0C; */',
'}',
'',
'.page-buttons {',
'  display: flex;',
'  gap: 5px;',
'  flex-wrap: wrap;',
'}',
'',
'.page-buttons button {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'gap: 8px;',
'width: 40;',
'height: 40;',
'padding-top: 12px;',
'padding-right: 16px;',
'padding-bottom: 12px;',
'padding-left: 16px;',
'border-radius: 4px;',
'background: #E2E2E2;',
'color: #ABB3C5;',
'border:none;',
'}',
'',
'.page-buttons .active-page {',
'  /* background-color: #333;',
'  color: white;',
'  font-weight: bold; */',
' font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'color: #2D416F;',
'border: none;',
'}',
'',
'.controls-actions {',
'  display: flex;',
'  align-items: center;',
'  gap: 10px;',
'}',
'',
'.search-input {',
'  padding: 8px 12px;',
'  border: 1px solid #ccc;',
'  border-radius: 4px;',
'  font-family: Helvetica;',
'  font-size: 14px;',
'  width: 200px;',
'}',
'',
'',
'@media (max-width: 600px) {',
'  .controls {',
'    flex-direction: column;',
'    align-items: stretch;',
'  }',
'',
'  .sort-btn,',
'  .add-btn {',
'    width: 100%;',
'  }',
'',
'  .pagination {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  table {',
'    font-size: 14px;',
'  }',
'}',
'',
'',
'',
'.ui-dialog-titlebar{',
'    align-items: center;',
'    text-align: center;',
'} ',
'',
'/** Ratings and Recommendations **/',
'.review-section {',
'  font-family: Helvetica;',
'  margin: 10px auto; ',
'  padding: 10px;  ',
'',
'}',
'',
'.review-box {',
'  /* background-color: #f9f9f9; */',
'  border-radius: 8px;',
'  padding: 8px 0;',
'  margin-top: 10px;',
'}',
'',
'.review-title{',
'      display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'}',
'',
'.review-actions {',
'  display: flex;',
'  gap: 10px;',
'}',
'',
'.action-btn {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'  border: none;',
'  padding: 5px 10px;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.action-btn.edit {',
'  background-color: #007bff;',
'  color: white;',
'}',
'',
'.action-btn.delete {',
'  background-color: #dc3545;',
'  color: white;',
'}',
'',
'.action-btn:hover {',
'  opacity: 0.85;',
'}',
'',
'.review-box strong{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.review-box p {',
'  margin: 10px 0;',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.reviewer {',
'  display: flex;',
'  align-items: center;',
'  margin-top: 10px;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'gap: 6px;',
'padding-top: 4px;',
'padding-right: 8px;',
'padding-bottom: 4px;',
'padding-left: 8px;',
'',
'}',
'',
'.reviewer-photo {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 8px;',
'}',
'',
'.reviewer-name {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 12px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'vertical-align: middle;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'.review-button {',
'  float: right;',
'  background-color: #007bff;',
'  color: white;',
'  border: none;',
'  padding: 8px 14px;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  /* margin-top: 15px; */',
'}',
'',
'.review-button:hover {',
'  background-color: #0056b3;',
'}',
'',
'.review-header {',
'  display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin: 5px 0 25px 0;',
'}',
'',
'.review-header h3{',
'    font-family: Helvetica;',
'    font-weight: 700;',
'    font-size: 18px;',
'    line-height: 100%;',
'    letter-spacing: 0%;',
'    color: #32373B;',
'    margin: 0;',
'}',
'',
'/* Responsive tweaks */',
'@media (max-width: 600px) {',
'  .description {',
'    font-size: 16px;;',
'  }',
'',
'  .name {',
'    font-size: 14px;',
'  }',
'',
'  .avatar {',
'    width: 1.75rem;',
'    height: 1.75rem;',
'  }',
'}',
'',
'/* Responsive rule */',
'@media (max-width: 600px) {',
'  .review-header {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  .review-button {',
'    align-self: flex-start;',
'  }',
'}',
'',
'.ratings-card {',
'  /* border-radius: 1.25rem; */',
'  background-color: transparent; /* remove background */',
'  border-radius: 0;              /* remove rounded corners */',
'  box-sizing: border-box;',
'  box-shadow: none;              ',
'  border: none;',
'  padding: 1rem;',
'  margin: 1rem 0;',
'  width: 100%;',
'  max-width: 800px;',
'  /* box-sizing: border-box;',
'  box-shadow: 0 2px 6px rgba(0,0,0,0.05);  */',
'}',
'',
'.description {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 16px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    color: #423B3B;',
'}',
'',
'.author {',
'  display: flex;',
'  align-items: center;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'}',
'',
'.avatar {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 0.5rem;',
'  object-fit: cover;',
'}',
'',
'.name {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 14px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    vertical-align: middle;',
'    text-transform: capitalize;',
'    color: #423B3B;',
'}',
'',
'/* Responsive tweaks */',
'@media (max-width: 600px) {',
'  .description {',
'    font-size: 16px;;',
'  }',
'',
'  .name {',
'    font-size: 14px;',
'  }',
'',
'  .avatar {',
'    width: 1.75rem;',
'    height: 1.75rem;',
'  }',
'}',
'',
'ul{',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'/* color: #7A7A7A; */',
'}',
'',
'.comp-desc{',
'        font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #7A7A7A;',
'}',
'',
'.showing{',
'  display: flex;',
'  gap: 24px;',
'  align-items: center;',
'  margin: 0 24px;',
'}',
'',
'ui-dialog-content ui-widget-content{',
'    padding: 25px;',
'}',
'',
'.a-AlertMessage{',
'    padding: 25px;',
'}',
'',
'.a-AlertMessage-icon{',
'    background-color: #D0E4FB;',
'     padding: 10px;',
'}',
'',
'.a-AlertMessage-title {',
'    font-family: Helvetica;',
'}',
'',
'.a-AlertMessage-details{',
'    font-family: Helvetica;',
'}',
'',
'js-confirmBtn ui-button ui-corner-all ui-widget ui-button--hot{',
'    font-family: Helvetica;',
'}',
'',
'/* Cancel button (optional separate styling) */',
'.ui-dialog.my-custom-class .ui-dialog-buttonpane .ui-button:contains("Cancel") {',
'  background-color: #e0e0e0;',
'  color: #333;',
'}',
'',
'',
'',
'.styled-table {',
'  width: 100%;',
'  border-collapse: collapse;',
'}',
'.styled-table th, .styled-table td {',
'  border: 1px solid #ccc;',
'  padding: 8px;',
'}',
'.styled-table th {',
'  background-color: #f4f4f4;',
'}',
'',
'.search-sort-row {',
'  display: flex;',
'  align-items: center;',
'  gap: 15px;',
'  flex-wrap: wrap; /* responsive fallback */',
'  margin-bottom: 10px;',
'}',
'',
'.search-input {',
'  padding: 8px;',
'  font-size: 14px;',
'  flex: 1 1 auto;',
'  min-width: 200px;',
'}',
'',
'.sort-container {',
'  display: flex;',
'  align-items: center;',
'  gap: 5px;',
'}',
'',
'#user-sort {',
'  padding: 8px;',
'  font-size: 14px;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-style: Bold;',
' line-height: 100%; ',
'letter-spacing: 0%;',
'border: 1.5px solid #348BEF;',
'border-radius: 4px;',
'  vertical-align: middle;     /* Helps vertical alignment */',
'  appearance: none;           /* Remove default styling */',
'}',
'',
'.sort-container label {',
'  text-transform: uppercase;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-style: Bold;',
'font-size: 14px;',
'leading-trim: NONE;',
'line-height: 100%;',
'letter-spacing: 0%;',
'}',
'',
'',
'.search-sort-region{',
'    display: flex;',
'    gap:15px;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'25'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(263993308665215947)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>3371237801798025892
,p_plug_display_sequence=>20
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'',
'BEGIN',
'  -- Fetch the companies from company table.',
' FOR i in (SELECT ',
'              company_id,',
'              company_name,',
'              company_desc,',
'              decode(company_status, ''A'', ''Active'', ''I'', ''Inactive'') status,',
'              img_url',
'             FROM XXMRKT.XXMRKT_COMPANY_LIST',
'             WHERE COMPANY_TYPE = ''Loan Services''',
'             AND COMPANY_cODE = :AP_COMPANY_CODE',
'             AND COMPANY_ID = :AP_COMPANY_ID',
'             ORDER BY 1',
') LOOP',
'  RETURN',
'        ''<div class="top-region-header">',
'                <div class = "internal-flex">',
'                    <div class="img-div">',
'                        <img class ="prod-img" src="https://testapp.softsuite.com/softsuite/api/mrkt/getimages/''||:AP_COMPANY_ID||''" alt="group">',
'                    </div>',
'                    <div class="text-set">',
'                        <p class="company_name">''||i.company_name||''</p>'';',
'                        if i.status = ''Active'' then',
'                            RETURN ''<span style="background:#ECFDF3">''||i.status||''</span>'';',
'                        else',
'                            RETURN ''<span>''||i.status||''</span>'';',
'                        end if;',
'             RETURN ''</div>',
'                </div>',
'          </div>    ',
'         '';',
'    END LOOP;',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(263994223443215956)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-TabsRegion-mod--simple'
,p_plug_template=>3223171818405608528
,p_plug_display_sequence=>60
,p_location=>null
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(263995127015215965)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:js-useLocalStorage:t-TabsRegion-mod--fillLabels:t-TabsRegion-mod--simple'
,p_plug_template=>3223171818405608528
,p_plug_display_sequence=>40
,p_location=>null
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(151822588833279628)
,p_plug_name=>'Denied'
,p_parent_plug_id=>wwv_flow_imp.id(263995127015215965)
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4501440665235496320
,p_plug_display_sequence=>40
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type   VARCHAR2(100);',
'    v_type        NUMBER;',
'    v_count       NUMBER;',
'    v_offset      NUMBER := NVL(:P6_DEND_OFFSET, 1);',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_DENIED_DATA'''''';',
'    v_item        VARCHAR2(100) := ''''''P6_DEND_OFFSET'''''';',
'    v_region      VARCHAR2(100) := ''''''denied'''''';',
'    v_r varchar2(100);',
'',
'BEGIN',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :AP_COMPANY_ID;',
'    EXCEPTION',
'        WHEN no_data_found THEN',
'            NULL;',
'    END;',
'           -- Count users for pagination',
'',
'          SELECT CEIL(COUNT(*) / v_page_size)',
'          INTO v_count',
'            FROM XXHRMS.XXHRMS_PEOPLE a',
'            JOIN XXMRKT.XXMRKT_APPLIED_LOANS b ON a.person_id = b.staff_id',
'            JOIN XXMRKT.XXMRKT_PRODUCT_LIST d ON b.product_id = d.product_id',
'            JOIN XXMRKT.XXMRKT_LOAN_TYPES c ON d.product_type = c.loan_type_id',
'            JOIN XXMRKT.XXMRKT_LOAN_STATUS e ON e.loan_id = b.loan_id',
'            WHERE ',
'                b.company_id = :P6_COMPANY_ID',
'                AND b.company_code = :AP_COMPANY_CODE',
'                AND e.approval_level = :AP_LEVEL',
'                AND e.approval_level IS NOT NULL',
'                AND e.status = ''DENIED''',
'               -- AND (e.disbursed_status = ''PENDING'' OR e.disbursed_status = ''DISBURSED'') ',
'            ORDER BY b.creation_date DESC;',
'',
'',
'        -- Render HTML if company type is Loan Services',
'         IF v_comp_type = ''Loan Services'' THEN',
'                    v_type := 1;',
'',
'                    IF v_offset < 1 THEN',
'                        v_offset := 1;',
'                    ELSIF v_offset > v_count THEN',
'                        v_offset := v_count;',
'                    END IF;',
'        -- Begin HTML Output',
'        htp.p(''',
'              <div class="controls">',
'                <h2>Denied Loans</h2>',
'                <div>',
'                  <input type="text" id="denied-approvals-search" placeholder="Search Denied Loans..." ',
'                         onkeyup="filterDenied()" class="search-input">',
'                </div>',
'              </div>',
'                <div class="table-wrapper">',
'                  <table>',
'                    <thead>',
'                      <tr>    ',
'						  <th>Employee ID</th>',
'						  <th>Employee Name</th>',
'						  <th>Loan Type</th>',
'						  <th>Loan Amount (Naira)</th>',
'						  <th> Status</th>',
'                          <th> Date</th>',
'                      </tr>',
'                    </thead>',
'                    <tbody id="denied-table-body">',
'					<!-- Dynamic rows go here -->',
'				  </tbody>',
'                </table>',
'              </div>'');',
'',
'      --paginatuon controls',
'         -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="page-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'              </div>',
'',
'              <div class="page-buttons">',
'                <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&lt;</button>'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                    END LOOP;',
'',
'                    htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&gt;</button>',
'            </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'    END IF;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ajax_items_to_submit=>'P6_DEND_OFFSET'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(151822675129279629)
,p_plug_name=>'Approved'
,p_parent_plug_id=>wwv_flow_imp.id(263995127015215965)
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4501440665235496320
,p_plug_display_sequence=>20
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type   VARCHAR2(100);',
'    v_type        NUMBER;',
'    v_count       NUMBER;',
'    v_offset      NUMBER := NVL(:P6_APPR_OFFSET, 1);',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_APPROVED_DATA'''''';',
'    v_item        VARCHAR2(100) := ''''''P6_APPR_OFFSET'''''';',
'    v_region      VARCHAR2(100) := ''''''approved'''''';',
'    v_r varchar2(100);',
'',
'BEGIN',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :AP_COMPANY_ID;',
'    EXCEPTION',
'        WHEN no_data_found THEN',
'            NULL;',
'    END;',
'',
'    IF :AP_LEVEL = 5 THEN',
'        v_r := ''Disbursed'';',
'    ELSE',
'        v_r := ''Approval'';',
'    END IF;',
'           -- Count users for pagination',
'',
'          SELECT CEIL(COUNT(*) / v_page_size)',
'          INTO v_count',
'            FROM XXHRMS.XXHRMS_PEOPLE a',
'            JOIN XXMRKT.XXMRKT_APPLIED_LOANS b ON a.person_id = b.staff_id',
'            JOIN XXMRKT.XXMRKT_PRODUCT_LIST d ON b.product_id = d.product_id',
'            JOIN XXMRKT.XXMRKT_LOAN_TYPES c ON d.product_type = c.loan_type_id',
'            JOIN XXMRKT.XXMRKT_LOAN_STATUS e ON e.loan_id = b.loan_id',
'            WHERE ',
'                b.company_id = :P6_COMPANY_ID',
'                AND b.company_code = :AP_COMPANY_CODE',
'                AND e.approval_level = :AP_LEVEL',
'                AND e.approval_level IS NOT NULL',
'                AND e.status = ''APPROVED''',
'                AND (e.disbursed_status = ''PENDING'' OR e.disbursed_status = ''DISBURSED'') ',
'            ORDER BY b.creation_date DESC;',
'',
'',
'        -- Render HTML if company type is Loan Services',
'         IF v_comp_type = ''Loan Services'' THEN',
'                    v_type := 1;',
'',
'                    IF v_offset < 1 THEN',
'                        v_offset := 1;',
'                    ELSIF v_offset > v_count THEN',
'                        v_offset := v_count;',
'                    END IF;',
'        -- Begin HTML Output',
'        htp.p(''',
'              <div class="controls">',
'                <h2>Approved Loans</h2>',
'                <div>',
'                  <input type="text" id="approved-search" placeholder="Search Approved Loans..." ',
'                         onkeyup="filterApproved()" class="search-input">',
'                </div>',
'              </div>',
'                <div class="table-wrapper">',
'                  <table>',
'                    <thead>',
'                      <tr>    ',
'						  <th>Employee ID</th>',
'						  <th>Employee Name</th>',
'						  <th>Loan Type</th>',
'						  <th>Loan Amount (Naira)</th>',
'						  <th> Status</th>',
'                          <th> Date</th>',
'                      </tr>',
'                    </thead>',
'                    <tbody id="approved-table-body">',
'					<!-- Dynamic rows go here -->',
'				  </tbody>',
'                </table>',
'              </div>'');',
'',
'      --paginatuon controls',
'         -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="page-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'              </div>',
'',
'              <div class="page-buttons">',
'                <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&lt;</button>'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                    END LOOP;',
'',
'                    htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&gt;</button>',
'            </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'    END IF;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(263995202455215966)
,p_plug_name=>'Pending'
,p_region_name=>'pending_table_region'
,p_parent_plug_id=>wwv_flow_imp.id(263995127015215965)
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4501440665235496320
,p_plug_display_sequence=>10
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type   VARCHAR2(100);',
'    v_type        NUMBER;',
'    v_count       NUMBER;',
'    v_offset      NUMBER := NVL(:P6_PEND_OFFSET, 1);',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_PENDING_DATA'''''';',
'    v_item        VARCHAR2(100) := ''''''P6_PEND_OFFSET'''''';',
'    v_region      VARCHAR2(100) := ''''''pending'''''';',
'',
'BEGIN',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :AP_COMPANY_ID;',
'    EXCEPTION',
'        WHEN no_data_found THEN',
'            NULL;',
'    END;',
'           -- Count users for pagination',
'',
'          SELECT CEIL(COUNT(*) / v_page_size)',
'          INTO v_count',
'          FROM ',
'				XXHRMS.XXHRMS_PEOPLE a',
'			JOIN ',
'				XXMRKT.XXMRKT_APPLIED_LOANS b',
'				ON a.person_id = b.staff_id',
'			JOIN ',
'				XXMRKT.XXMRKT_PRODUCT_LIST d',
'				ON b.product_id = d.product_id',
'			JOIN ',
'				XXMRKT.XXMRKT_LOAN_TYPES c',
'				ON d.product_type = c.loan_type_id',
'			LEFT JOIN ',
'				XXMRKT.XXMRKT_LOAN_STATUS e',
'				ON e.loan_id = b.loan_id',
'				AND e.approval_level = :AP_LEVEL',
'			WHERE ',
'				b.company_id = :P6_COMPANY_ID',
'				AND b.company_code = :AP_COMPANY_CODE',
'                AND e.approval_level IS NOT NULL',
'				AND (',
'					(:AP_LEVEL = 1 AND b.loan_status = ''INITIATED'')',
'					OR ',
'					(:AP_LEVEL BETWEEN 2 AND 5 AND e.status = ''PENDING'')',
'					   )',
'			ORDER BY ',
'				b.creation_date DESC;',
'',
'        -- Render HTML if company type is Loan Services',
'                IF v_comp_type = ''Loan Services'' THEN',
'                    v_type := 1;',
'',
'                    IF v_offset < 1 THEN',
'                        v_offset := 1;',
'                    ELSIF v_offset > v_count THEN',
'                        v_offset := v_count;',
'                    END IF;',
'        -- Begin HTML Output',
'        htp.p(''',
'              <div class="controls">',
'                <h2>Pending Loans</h2>',
'                <div class="search-sort-region">',
'                    <div class="sort-container">',
'                      <select id="user-sort" onchange="handleSortChange(this)">',
'                      <option value="">Sort By</option>',
'                        <option value="EMPLOYEE_ID">Employee ID</option>',
'                        <option value="LOAN_TYPE">Loan Type</option>',
'                        <option value="LOAN_AMOUNT">Loan Amount</option>',
'                        <option value="CREATION_DATE">Approved Status</option>',
'                      </select>',
'                   </div>',
'                  <input type="text" id="pending-approvals-search" placeholder="Search Pending Approvals..." ',
'                         onkeyup="filterPending()" class="search-input">',
'                </div>',
'              </div>',
'                <div class="table-wrapper">',
'                  <table>',
'                    <thead>',
'                      <tr>    ',
'						  <th>Employee ID</th>',
'						  <th>Employee Name</th>',
'						  <th>Loan Type</th>',
'						  <th>Loan Amount (Naira)</th>',
'						  <th> Status</th>',
'						  <th>Action</th>',
'                      </tr>',
'                    </thead>',
'                    <tbody id="pending-table-body">',
'					<!-- Dynamic rows go here -->',
'				  </tbody>',
'                </table>',
'              </div>'');',
'',
'      --paginatuon controls',
'         -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="page-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'              </div>',
'',
'              <div class="page-buttons">',
'                <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&lt;</button>'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                    END LOOP;',
'',
'                    htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&gt;</button>',
'            </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'    END IF;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(263995438559215969)
,p_plug_name=>'Ratings and Recommendations'
,p_parent_plug_id=>wwv_flow_imp.id(263995127015215965)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>50
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'',
'BEGIN',
'htp.p(''<div class="review-section id="rating">',
'            <div onclick="return" class="review-header">',
'            <h3>Reviews/Recommendations</h3>',
'          </div>'');',
'        FOR i IN (select review_id,',
'                         decode(rating, 5, ''Excellent'', 4, ''Very Good'', 3, ''Average'', 2, ''Poor'', 1, ''Bad/ Avoid Product'', 0, ''Not Rated'') rating,',
'                         comments,',
'                         reviewer_name,',
'                         reviewer_id',
'                    from XXMRKT.XXMRKT_PRODUCT_REVIEWS',
'                    where COMPANY_ID = :AP_COMPANY_ID',
'                    and COMPANY_CODE = :AP_COMPANY_CODE',
'                  ) ',
'        LOOP',
'        htp.p( ',
'        ''',
'          <div class="review-box">',
'             <div class="review-title">',
'                <strong>Product Rating - ''||i.rating||''</strong>',
'            </div>',
'            <p>',
'              ''||i.comments||''',
'            </p>',
'            ',
'            <div class="reviewer">',
'              <img src="https://testapp.softsuite.com/softsuite/api/mrkt/getreviewerimage/''||i.reviewer_id||''" alt="Reviewer Photo" class="reviewer-photo">',
'              <span class="reviewer-name">''||i.reviewer_name||''</span>',
'            </div>',
'          </div>''',
'        );',
'    END LOOP;',
' htp.p(''</div>',
'',
''');',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_plug_display_condition_type=>'NEVER'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(150086807659240701)
,p_name=>'P6_APPR_OFFSET'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(263994223443215956)
,p_item_default=>'1'
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(150087506977240708)
,p_name=>'P6_PEND_OFFSET'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(263994223443215956)
,p_item_default=>'1'
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(150422785576173897)
,p_name=>'P6_DEND_OFFSET'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_imp.id(263994223443215956)
,p_item_default=>'1'
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(264002312469216248)
,p_name=>'P6_COMPANY_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(263994223443215956)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(76262836400219005)
,p_name=>'New'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(76263372269219007)
,p_event_id=>wwv_flow_imp.id(76262836400219005)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'apex.util.getTopApex().jQuery(".modal-dialog--pullout .ui-dialog-title").prepend(''<img src="#APP_IMAGES#Featured icon.png" style="height:48px;"/>'');'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(76263881558219010)
,p_event_id=>wwv_flow_imp.id(76262836400219005)
,p_event_result=>'TRUE'
,p_action_sequence=>50
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'if($v(''P6_APPR_OFFSET'' == 0)){',
'    $(''#actionButton'').attr(''disabled'',''disabled'');',
'',
'}'))
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(76261208986219000)
,p_process_sequence=>10
,p_process_point=>'BEFORE_HEADER'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'New'
,p_process_sql_clob=>':P6_COMPANY_ID := :AP_COMPANY_ID;'
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>76261208986219000
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(76262419944219004)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_PENDING_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'     v_page_size number := 5;',
'BEGIN',
'   :P6_PEND_OFFSET := apex_application.g_x02;',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'SELECT ',
'    a.person_id,',
'    INITCAP(a.full_name) AS full_name,',
'    d.product_id,',
'    d.product_type,',
'    c.loan_type_id,',
'    c.loan_type,',
'    b.loan_id,',
'    TO_CHAR(b.loan_amount, ''999G999G999G999G990D00'') AS loan_amount,',
'',
'    -- Dynamic status logic',
'    CASE ',
'        WHEN NVL(:AP_LEVEL, 0) = 1 THEN b.loan_status',
'        WHEN :AP_LEVEL IS NOT NULL THEN b.loan_status',
'        ELSE e.status',
'    END AS status_result,',
'',
'    b.company_id,',
'    e.approval_level',
'FROM ',
'    XXMRKT.XXMRKT_APPLIED_LOANS b',
'JOIN ',
'    XXHRMS.XXHRMS_PEOPLE a ON a.person_id = b.staff_id',
'JOIN ',
'    XXMRKT.XXMRKT_PRODUCT_LIST d ON b.product_id = d.product_id',
'JOIN ',
'    XXMRKT.XXMRKT_LOAN_TYPES c ON d.product_type = c.loan_type_id',
'LEFT JOIN ',
'    XXMRKT.XXMRKT_LOAN_STATUS e ',
'    ON e.loan_id = b.loan_id',
'    --AND (:AP_LEVEL BETWEEN 2 AND 5) ',
'WHERE ',
'    b.company_id = :P6_COMPANY_ID',
'    AND b.company_code = :AP_COMPANY_CODE',
'    AND (',
'        (:AP_LEVEL = 1 AND b.loan_status = ''INITIATED'')',
'        OR ',
'        (:AP_LEVEL BETWEEN 2 AND 5 AND e.status = ''PENDING'')',
'    )',
'ORDER BY ',
'    b.creation_date DESC',
')',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''personId'', pro_rec.person_id);',
'    apex_json.write(''productId'', pro_rec.product_id);',
'    apex_json.write(''fullName'', pro_rec.full_name);',
'    apex_json.write(''loanType'', pro_rec.loan_type);',
'    apex_json.write(''loanAmount'', pro_rec.loan_amount);',
'    apex_json.write(''status'', initcap(pro_rec.status_result));',
'    apex_json.write(''companyID'', pro_rec.company_id);',
'    apex_json.write(''loanId'', pro_rec.loan_id);',
'    apex_json.write(''productTYPE'', pro_rec.product_type);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>76262419944219004
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(76261600990219003)
,p_process_sequence=>20
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_APPROVED_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_page_size number := 5;',
'BEGIN',
'    :P17_USERS_OFFSET := apex_application.g_x02;',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'  SELECT ',
'    a.person_id,',
'    initcap(a.full_name) full_name,',
'    d.product_id,',
'    d.product_type,',
'    c.loan_type_id,',
'    c.loan_type,',
'    b.loan_id,',
'    to_char(b.loan_amount, ''999G999G999G999G990D00'') loan_amount,',
'    b.loan_status,',
'    b.company_id,',
'    e.approval_level,',
'    e.disbursed_status,',
'    e.status,',
'    to_char(e.created_date, ''Day, DD Month YYYY'') created_date,',
'    to_char(b.disbursed_date, ''Day, DD Month YYYY'') disbursed_date',
'FROM ',
'    XXHRMS.XXHRMS_PEOPLE a',
'JOIN ',
'    XXMRKT.XXMRKT_APPLIED_LOANS b',
'    ON a.person_id = b.staff_id',
'JOIN ',
'    XXMRKT.XXMRKT_PRODUCT_LIST d',
'    ON b.product_id = d.product_id',
'JOIN ',
'    XXMRKT.XXMRKT_LOAN_TYPES c',
'    ON d.product_type = c.loan_type_id',
'JOIN ',
'    XXMRKT.XXMRKT_LOAN_STATUS e',
'    ON e.loan_id = b.loan_id',
'WHERE ',
'    b.company_id = :P6_COMPANY_ID',
'    AND b.company_code = :AP_COMPANY_CODE',
'    AND E.APPROVAL_LEVEL = :AP_LEVEL',
'    AND e.approval_level IS NOT NULL',
'    and e.status = ''APPROVED''',
'    --and e.disbursed_status = ''PENDING'' OR E.DISBURSED_STATUS = ''DISBURSED''',
'ORDER BY ',
'    b.creation_date DESC',
'',
')',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''personId'', pro_rec.person_id);',
'    apex_json.write(''fullName'', pro_rec.full_name);',
'    apex_json.write(''loanType'', pro_rec.loan_type);',
'    apex_json.write(''loanAmount'', pro_rec.loan_amount);',
'    apex_json.write(''status'', initcap(pro_rec.status));',
'    apex_json.write(''approvalDate'', initcap(pro_rec.created_date));',
'    apex_json.write(''disbursedDate'', initcap(pro_rec.disbursed_date));',
'    apex_json.write(''approvalLevel'', initcap(pro_rec.approval_level));',
'    apex_json.write(''companyID'', pro_rec.company_id);',
'    apex_json.write(''productTYPE'', pro_rec.product_type);',
'    apex_json.write(''disbursedStatus'', initcap(pro_rec.disbursed_status));',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>76261600990219003
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(76262058639219004)
,p_process_sequence=>30
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_DENIED_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_page_size number := 5;',
'BEGIN',
'    :P6_DEND_OFFSET := apex_application.g_x02;',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'  SELECT ',
'    a.person_id,',
'    initcap(a.full_name) full_name,',
'    d.product_id,',
'    d.product_type,',
'    c.loan_type_id,',
'    c.loan_type,',
'    b.loan_id,',
'    to_char(b.loan_amount, ''999G999G999G999G990D00'') loan_amount,',
'    b.loan_status,',
'    b.company_id,',
'    e.approval_level,',
'    e.disbursed_status,',
'    e.status,',
'    to_char(e.created_date, ''Day, DD Month YYYY'') created_date,',
'    to_char(b.disbursed_date, ''Day, DD Month YYYY'') disbursed_date',
'FROM ',
'    XXHRMS.XXHRMS_PEOPLE a',
'JOIN ',
'    XXMRKT.XXMRKT_APPLIED_LOANS b',
'    ON a.person_id = b.staff_id',
'JOIN ',
'    XXMRKT.XXMRKT_PRODUCT_LIST d',
'    ON b.product_id = d.product_id',
'JOIN ',
'    XXMRKT.XXMRKT_LOAN_TYPES c',
'    ON d.product_type = c.loan_type_id',
'JOIN ',
'    XXMRKT.XXMRKT_LOAN_STATUS e',
'    ON e.loan_id = b.loan_id',
'WHERE ',
'    b.company_id = :P6_COMPANY_ID',
'    AND b.company_code = :AP_COMPANY_CODE',
'    AND E.APPROVAL_LEVEL = :AP_LEVEL',
'    AND e.approval_level IS NOT NULL',
'    and e.status = ''DENIED''',
'ORDER BY ',
'    b.creation_date DESC',
'',
')',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''personId'', pro_rec.person_id);',
'    apex_json.write(''fullName'', pro_rec.full_name);',
'    apex_json.write(''loanType'', pro_rec.loan_type);',
'    apex_json.write(''loanAmount'', pro_rec.loan_amount);',
'    apex_json.write(''deniedStatus'', initcap(pro_rec.status));',
'    apex_json.write(''deniedDate'', pro_rec.created_date);',
'    apex_json.write(''disbursedDate'', pro_rec.disbursed_date);',
'    apex_json.write(''disbursedStatus'', pro_rec.disbursed_status);',
'    apex_json.write(''approvalLevel'', pro_rec.approval_level);',
'    apex_json.write(''companyID'', pro_rec.company_id);',
'    apex_json.write(''productTYPE'', pro_rec.product_type);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>76262058639219004
);
wwv_flow_imp.component_end;
end;
/
