prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/test.sql
@@application/shared_components/navigation/lists/lenders_reports.sql
@@application/shared_components/navigation/lists/lenders_menu.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/featured_icon_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/set_application_items.sql
@@application/shared_components/logic/application_processes/prepare_url.sql
@@application/shared_components/logic/application_items/ap_company_code.sql
@@application/shared_components/logic/application_items/ap_company_id.sql
@@application/shared_components/logic/application_items/ap_company_name.sql
@@application/shared_components/logic/application_items/ap_level.sql
@@application/shared_components/logic/application_items/ap_user_id.sql
@@application/shared_components/logic/application_items/ap_user_name.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/approver_name.sql
@@application/shared_components/user_interface/lovs/disbursed_date.sql
@@application/shared_components/user_interface/lovs/lenders_nav_list.sql
@@application/shared_components/user_interface/lovs/loan_types.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report_loan_application.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report_approved_loan_report.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report_rejected_loan_report.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report_disbursed_loan_report.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report_loan_status_report.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report_borrower_profile_report.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb_report_user_creation_report.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/marketplace_authentication.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00019.sql
@@application/pages/page_00021.sql
@@application/pages/page_00023.sql
@@application/pages/page_00025.sql
@@application/pages/page_00027.sql
@@application/pages/page_00029.sql
@@application/pages/page_00031.sql
@@application/pages/page_00033.sql
@@application/pages/page_09999.sql
@@application/pages/page_10002.sql
@@application/pages/page_10009.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
