prompt --application/pages/page_00002
begin
--   Manifest
--     PAGE: 00002
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>3780766536418114
,p_default_application_id=>2000008
,p_default_id_offset=>0
,p_default_owner=>'XXSBS'
);
wwv_flow_imp_page.create_page(
 p_id=>2
,p_name=>'Company Setup'
,p_alias=>'COMPANY-SETUP'
,p_step_title=>'Company Setup'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/** Products JS */',
'/**',
' * Dynamic Product Table with Pagination',
' * -------------------------------------',
' */',
'',
'let productData = [];',
'let approversData = [];',
'let usersData = [];',
'let currentPage = 1;',
'// Data Fetchers',
'const getData = (offset, process, type) => {',
'  apex.server.process(process, {',
'    x01: $v(''P2_COMPANY_ID''),',
'    x02: offset',
'  }, {',
'    dataType: "json",',
'    success: function(data) {',
'        if(type === ''users''){',
'            usersData = [...data];',
'            renderUsersTablePage(offset);',
'        }',
'        if(type === ''products''){',
'            productData = [...data];  ',
'            renderTablePage(offset);',
'        }',
'        if(type === ''approvers''){',
'            approversData = [...data];',
'            renderApproversTablePage(offset);',
'        }',
'        const select = document.getElementById(`${type}-select`);',
'            if (select) {',
'                select.value = offset;',
'        }',
'    },',
'    error: function(jqXHR, textStatus, errorThrown) {',
'      console.error("Error loading product data:", textStatus, errorThrown);',
'    }',
'  });',
'  return false;',
'};',
'',
'// Pagination Handler',
'function apprPaginate(direction, process, item, type, totalCount) {',
'  let current = parseInt($v(item)) || 0;',
'  //const pageSize = 1;',
'  let newOffset = current + (direction);',
'  if (newOffset < 1) newOffset = 1;',
'  if (newOffset > totalCount) newOffset = totalCount;',
'  $s(item, newOffset);',
'  getData(newOffset, process, type);',
'  return false;',
'}',
'',
'function handlePageChange(selectElement, process, item, type) {',
'  const selectedValue = parseInt(selectElement.value);',
'  console.log("Selected page:", selectedValue);',
'  $s(item, selectedValue);',
'  getData(selectedValue, process, type);',
'  return false;',
'}',
'',
'// Table Rendering Functions',
'const tableBody = document.getElementById("product-table-body");',
'const approversTableBody = document.getElementById("approvers-table-body");',
'const usersTableBody = document.getElementById("users-table-body");',
'',
'function renderTablePage(page) {',
'  tableBody.innerHTML = "";',
'',
'    const rowsPerPage = 5;',
'    const start = (page - 1) * rowsPerPage;',
'    const end = start + rowsPerPage;',
'    const pageData = productData.slice(start, end);',
'',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    row.innerHTML = `',
'      <td>${item.productName}</td>',
'      <td>${item.productType}</td>',
'      <td>${item.interestRate}</td>',
'      <td>${item.minimumLimits}</td>',
'      <td>${item.maximumLimits}</td>',
'      <td>${item.minimumRepaymentPeriod}</td>',
'      <td>${item.maximumRepaymentPeriod}</td>',
'      <td>${item.chargesType === ''%'' ? item.charges + item.chargesType : item.chargesType + item.charges}</td>',
'      <td>${item.insuranceFeesType === ''%'' ? item.insuranceFees + item.insuranceFeesType : item.insuranceFeesType + item.insuranceFees}</td>',
'      <td><span class="status ${item.status.toLowerCase()}">${item.status}</span></td>',
unistr('      <td><a href="#" onclick="return redirectToModalPageUpdateProduct(8, ${item.companyID}, ${item.productID})">Edit \270E</a></td>'),
'    `;',
'    tableBody.appendChild(row);',
'  });',
'}',
'',
'function renderApproversTablePage(page) {',
'  approversTableBody.innerHTML = "";',
'  ',
'    const rowsPerPage = 5;',
'    const start = (page - 1) * rowsPerPage;',
'    const end = start + rowsPerPage;',
'    const pageData = approversData.slice(start, end);',
'	',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    row.innerHTML = `',
'      <td>${item.userName}</td>',
'      <td>${item.fullName || ''''}</td>',
'      <td>${item.emailAddress}</td>',
'      <td>${item.approvalLevel}</td>',
'      <td><span class="status ${item.status.toLowerCase()}">${item.status}</span></td>',
unistr('      <td><a href="#" onclick="return redirectToModalPage5UpdateProduct(5, ${item.companyID}, ${item.Id})">Edit \270E</a></td>'),
'    `;',
'    approversTableBody.appendChild(row);',
'  });',
'}',
'',
'function renderUsersTablePage(page) {',
'  usersTableBody.innerHTML = "";',
'',
'    const rowsPerPage = 5;',
'    const start = (page - 1) * rowsPerPage;',
'    const end = start + rowsPerPage;',
'    const pageData = usersData.slice(start, end);',
'',
'  pageData.forEach(item => {',
'    const row = document.createElement("tr");',
'    row.innerHTML = `',
'      <td>${item.userName}</td>',
'      <td>${item.fullName || ''''}</td>',
'      <td>${item.emailAddress}</td>',
'      <td><span class="status ${item.status.toLowerCase()}">${item.status}</span></td>',
unistr('      <td><a href="#" onclick="return redirectToModalPage7UpdateProduct(7, ${item.companyID}, ${item.userId})">Edit \270E</a></td>'),
'    `;',
'    usersTableBody.appendChild(row);',
'  });',
'}',
'',
'function filterProducts() {',
'  const input = document.getElementById(''product-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#product-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'function filterApprovers() {',
'  const input = document.getElementById(''approvers-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#approvers-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'function filterUsers() {',
'  const input = document.getElementById(''users-search'');',
'  const filter = input.value.toLowerCase();',
'  document.querySelectorAll(''#users-table-body tr'').forEach(row => {',
'    row.style.display = row.textContent.toLowerCase().includes(filter) ? '''' : ''none'';',
'  });',
'}',
'',
'',
'// Modal Redirect Helpers',
'const modal = document.getElementById(''main-modal'');',
'',
'function afterLoad() {',
'  apex.message.showPageSuccess(''success'');',
'}',
'',
'// Redirect Function Generator',
'const redirectToModalPageEditCompany = (pageID, compID) => generateEditURL(pageID, compID);',
'const redirectToModalPageCreateProduct = (pageID, compID, compType) => generateModalURL(pageID, compID, compType);',
'const redirectToModalPageCreateApprovers = (pageID, compID, compType) => generateModalURL(pageID, compID, compType);',
'const redirectToModalPageUpdateProduct = (pageID, compID, productID) => generateUpdateURL(pageID, compID, productID, ''P8_COMPANY_ID'', ''P8_PRODUCT_ID'');',
'const redirectToModalPage5UpdateProduct = (pageID, compID, userID) => generateUpdateURL(pageID, compID, userID, ''P5_COMPANY_ID'', ''P5_ID'');',
'const redirectToModalPage7UpdateProduct = (pageID, compID, userID) => generateUpdateURL(pageID, compID, userID, ''P7_COMPANY_ID'', ''P7_USER_ID'');',
'',
'// URL Builders',
'function generateEditURL(pageID, compID) {',
'  let url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P${pageID}_COMPANY_ID:${compID}`;',
'  applyRedirect(url);',
'  return false;',
'}',
'',
'function generateModalURL(pageID, compID, compType) {',
'  let url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:P${pageID}_COMPANY_ID,P${pageID}_COMPANY_CAT:${compID},${compType}`;',
'  applyRedirect(url);',
'  return false;',
'}',
'',
'function generateUpdateURL(pageID, compID, recordID, compParam, idParam) {',
'  let url = `f?p=#APP_ID#:${pageID}:#SESSION#::NO:RP,${pageID}:${compParam},${idParam}:${compID},${recordID}`;',
'  applyRedirect(url);',
'  return false;',
'}',
'',
'function applyRedirect(url) {',
'  url = url.replace("#APP_ID#", &APP_ID.).replace("#SESSION#", &SESSION.);',
'  apex.server.process("PREPARE_URL", { x01: url }, {',
'    success: function(pData) {',
'      if (pData.success === true) {',
'        apex.navigation.redirect(pData.url);',
'      } else {',
'        console.log("FALSE");',
'      }',
'    },',
'    error: function(request, status, error) {',
'      console.log("status:", status, "error:", error);',
'    }',
'  });',
'}',
'',
'// Initial Data Load',
'window.onload = () => {',
'  getData(1, ''GET_DATA'', ''products'');',
'  getData(1, ''GET_APPROVERS_DATA'', ''approvers'');',
'  getData(1, ''GET_USER_DATA'', ''users'');',
'',
'  renderTablePage(currentPage);',
'  renderApproversTablePage(currentPage);',
'  renderUsersTablePage(currentPage);',
'};',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.table-wrapper {',
'  overflow-x: auto;',
'  /* padding: 0 8px; */',
'  width: 100%;',
'}',
'',
'/*Back Button*/',
'.icon-button {',
'  display: flex;',
'  align-items: center; /* Vertically center the icon and text */',
'  /* padding: 20px 0px; */',
'  background: #FFFFFF;',
'  color: #000000;',
'  border: none;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  font-size: 16px;',
'  transition: background-color 0.3s;',
'  margin: 8px 0;',
'}',
'',
'',
'.icon {',
'  width: 20px; /* Set the width of the icon */',
'  height: 20px; /* Set the height of the icon */',
'  margin-right: 10px; /* Space between icon and text */',
'}',
'',
'',
'.button-text {',
'  white-space: nowrap; /* Prevent the text from breaking onto a new line */',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 18.4px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none;',
'}',
'',
'a{',
'    color: #7A7A7A;',
'}',
'',
'.product-description2 li{',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-style: Regular;',
'font-size: 14px;',
'leading-trim: NONE;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #7A7A7A;',
'}',
'/*Company image and name*/',
'.internal-flex{',
'  display: flex;',
'  flex-wrap: wrap;',
'  align-items:center;',
'  margin: 20px 0;',
'}',
'',
'.img-div{',
'    padding: 4px;',
'    width: 48px;         /* Set the width of the div */',
'    height: 48px;       /* Set the height of the div */',
'    overflow: hidden; ',
'    margin-right:16px;',
'    border-radius: 4px;',
'    opacity: 0px;',
'    border: 1px solid #DDDDDD;',
'    position: relative;',
'}',
'',
'.prod-img{',
'   width: 100%;         /* Ensures the image width is 100% of the div */',
'    height: 100%;        /* Ensures the image height is 100% of the div */',
'    object-fit: cover;   /* The image will cover the div while maintaining its aspect ratio */',
'     max-width: 100%;  /* Image will never exceed the width of its container */',
'     box-sizing: border-box; /* Ensures padding is taken into account */',
'}',
'',
'.text-set p{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 20px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'/**Tabs styling**/',
'.t-Tabs{',
'    border-bottom: 1px solid #E5E5E5;',
'}',
'',
'.t-Body .t-Tabs--simple .t-Tabs-link{',
'        color:#7A7A7A;',
'        text-decoration: none;',
'    border-top: 1px solid #ddd;',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'text-align: center;',
'}',
'',
'/** Company Description **/',
'.description-header{',
'    font-family: Helvetica;',
'    font-size: 16px;',
'    font-weight: 700;',
'    line-height: 24px;',
'    text-align: left;',
'    text-underline-position: from-font;',
'    text-decoration-skip-ink: none; ',
'    width: Fill (531px)px;',
'    height: Fixed (48px)px;',
'    padding: 8px 0px 0px 0px;',
'    gap: 8px;',
'    border-radius: 4px 0px 0px 0px;',
'    opacity: 0px;',
'    color: #423B3B;',
'}',
'',
'/**Edit Button **/',
'',
'.edit-button {',
'  display: inline-flex;',
'  align-items: center;',
'  padding: 16px 16px 16px 0px;',
'  background-color: white;',
'  margin: 20px 0px 5px 0px;',
'  color: #1e90ff;',
'  border: none;',
'  font-size: 14px;',
'  font-weight: 500;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  transition: 0.3s;',
'}',
'',
'.edit-button .icon {',
'  width: 16px;',
'  height: 16px;',
'  margin-right: 6px;',
'  filter: invert(37%) sepia(95%) saturate(1354%) hue-rotate(189deg) brightness(95%) contrast(101%);',
'}',
'',
'/*.edit-button:hover {',
'  background-color: #e6f3ff;',
'}*/',
'',
'',
'/*Products table css*/',
'',
'.controls {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 10px;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin-bottom: 15px;',
'}',
'',
'.controls h2{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 18px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #32373B;',
'}',
'',
'.sort-btn{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.add-btn {',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'  padding: 10px 14px;',
'  border: none;',
'  border-radius: 4px;',
'  cursor: pointer;',
'  background: #348BEF;',
'}',
'',
'.sort-btn {',
'  background-color: #f2f2f2;',
'}',
'',
'.add-btn {',
'  background-color: #007bff;',
'  color: #fff;',
'}',
'',
'.table-wrapper {',
'  overflow-x: auto;',
'}',
'',
'table {',
'  width: 100%;',
'  border-collapse: collapse;',
'  margin-bottom: 20px;',
'  min-width: 800px;',
'}',
'',
'thead {',
'  background-color:#2C2E2F;',
'  color: white;',
'}',
'',
'th{',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #F6F7F9;',
'}',
'',
'td {',
'  padding: 12px;',
'  text-align: left;',
'  border-bottom: 1px solid #ddd;',
'  white-space: nowrap;',
'  font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #7A7A7A; ',
'}',
'',
'.status {',
'  padding: 4px 10px;',
'  border-radius: 10px;',
'  font-size: 0.9em;',
'  display: inline-block;',
'}',
'',
'.status.active {',
'  background-color: #d4f8d4;',
'  color: #2d7f2d;',
'}',
'',
'.status.inactive {',
'  background-color: #f8d4d4;',
'  color: #a94442;',
'}',
'',
'.status.enabled {',
'  background-color: #d4f8d4;',
'  color: #2d7f2d;',
'}',
'',
'.status.disabled {',
'  background-color: #f8d4d4;',
'  color: #a94442;',
'}',
'',
'.pagination {',
'  display: flex;',
'  flex-wrap: wrap;',
'  gap: 10px;',
'  align-items: center;',
'  justify-content: space-between;',
'  padding: 30px 0px;',
'}',
'',
'.pagination select {',
'  padding: 5px;',
'  width: 81;',
'height: 40;',
'left: 91px;',
'opacity: 0.4;',
'border-radius: 6px;',
'font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'color: #0C0C0C;',
'}',
'',
'.pagination span{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 14px;',
'line-height: 100%;',
'letter-spacing: 0%;',
'/* color: #0C0C0C; */',
'}',
'',
'.pagination-ellipsis {',
'  display: inline-block;',
'  padding: 8px 12px;',
'  margin: 0 4px;',
'  background-color: #e0e0e0; /* Match button background */',
'  color: #888;',
'  border-radius: 6px;',
'  font-weight: bold;',
'  min-width: 32px;',
'  text-align: center;',
'  font-family: Arial, sans-serif;',
'}',
'',
'.page-buttons {',
'  display: flex;',
'  gap: 5px;',
'  flex-wrap: wrap;',
'}',
'',
'.page-buttons button {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'gap: 8px;',
'width: 40;',
'height: 40;',
'padding-top: 12px;',
'padding-right: 16px;',
'padding-bottom: 12px;',
'padding-left: 16px;',
'border-radius: 4px;',
'background: #E2E2E2;',
'color: #ABB3C5;',
'border:none;',
'}',
'',
'.page-buttons .active-page {',
'  /* background-color: #333;',
'  color: white;',
'  font-weight: bold; */',
' font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 16px;',
'letter-spacing: 0%;',
'color: #2D416F;',
'border: none;',
'}',
'',
'.controls-actions {',
'  display: flex;',
'  align-items: center;',
'  gap: 10px;',
'}',
'',
'.search-input {',
'  padding: 8px 12px;',
'  border: 1px solid #ccc;',
'  border-radius: 4px;',
'  font-family: Helvetica;',
'  font-size: 14px;',
'  width: 200px;',
'}',
'',
'',
'@media (max-width: 600px) {',
'  .controls {',
'    flex-direction: column;',
'    align-items: stretch;',
'  }',
'',
'  .sort-btn,',
'  .add-btn {',
'    width: 100%;',
'  }',
'',
'  .pagination {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  table {',
'    font-size: 14px;',
'  }',
'}',
'',
'',
'',
'.ui-dialog-titlebar{',
'    align-items: center;',
'    text-align: center;',
'} ',
'',
'/** Ratings and Recommendations **/',
'.review-section {',
'  font-family: Helvetica;',
'  margin: 10px auto; ',
'  padding: 10px;  ',
'',
'}',
'',
'.review-box {',
'  /* background-color: #f9f9f9; */',
'  border-radius: 8px;',
'  padding: 8px 0;',
'  margin-top: 10px;',
'}',
'',
'.review-title{',
'      display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'}',
'',
'.review-actions {',
'  display: flex;',
'  gap: 10px;',
'}',
'',
'.action-btn {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'  border: none;',
'  padding: 5px 10px;',
'  border-radius: 4px;',
'  cursor: pointer;',
'}',
'',
'.action-btn.edit {',
'  background-color: #007bff;',
'  color: white;',
'}',
'',
'.action-btn.delete {',
'  background-color: #dc3545;',
'  color: white;',
'}',
'',
'.action-btn:hover {',
'  opacity: 0.85;',
'}',
'',
'.review-box strong{',
'    font-family: Helvetica;',
'font-weight: 700;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.review-box p {',
'  margin: 10px 0;',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 14px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #423B3B;',
'}',
'',
'.reviewer {',
'  display: flex;',
'  align-items: center;',
'  margin-top: 10px;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'gap: 6px;',
'padding-top: 4px;',
'padding-right: 8px;',
'padding-bottom: 4px;',
'padding-left: 8px;',
'',
'}',
'',
'.reviewer-photo {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 8px;',
'}',
'',
'.reviewer-name {',
'  font-family: Helvetica;',
'font-weight: 400;',
'font-size: 12px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'vertical-align: middle;',
'text-transform: capitalize;',
'color: #423B3B;',
'}',
'',
'.review-button {',
'  float: right;',
'  background-color: #007bff;',
'  color: white;',
'  border: none;',
'  padding: 8px 14px;',
'  border-radius: 5px;',
'  cursor: pointer;',
'  /* margin-top: 15px; */',
'}',
'',
'.review-button:hover {',
'  background-color: #0056b3;',
'}',
'',
'.review-header {',
'  display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'  text-align: center;',
'  margin: 5px 0 25px 0;',
'}',
'',
'.review-header h3{',
'    font-family: Helvetica;',
'    font-weight: 700;',
'    font-size: 18px;',
'    line-height: 100%;',
'    letter-spacing: 0%;',
'    color: #32373B;',
'    margin: 0;',
'}',
'',
'/* Responsive tweaks */',
'@media (max-width: 600px) {',
'  .description {',
'    font-size: 16px;;',
'  }',
'',
'  .name {',
'    font-size: 14px;',
'  }',
'',
'  .avatar {',
'    width: 1.75rem;',
'    height: 1.75rem;',
'  }',
'}',
'',
'/* Responsive rule */',
'@media (max-width: 600px) {',
'  .review-header {',
'    flex-direction: column;',
'    align-items: flex-start;',
'  }',
'',
'  .review-button {',
'    align-self: flex-start;',
'  }',
'}',
'',
'.ratings-card {',
'  /* border-radius: 1.25rem; */',
'  background-color: transparent; /* remove background */',
'  border-radius: 0;              /* remove rounded corners */',
'  box-sizing: border-box;',
'  box-shadow: none;              ',
'  border: none;',
'  padding: 1rem;',
'  margin: 1rem 0;',
'  width: 100%;',
'  max-width: 800px;',
'  /* box-sizing: border-box;',
'  box-shadow: 0 2px 6px rgba(0,0,0,0.05);  */',
'}',
'',
'.description {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 16px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    color: #423B3B;',
'}',
'',
'.author {',
'  display: flex;',
'  align-items: center;',
'  background: #F7F7F7;',
'  border-radius: 30px;',
'}',
'',
'.avatar {',
'  width: 20px;',
'  height: 20px;',
'  border-radius: 50%;',
'  margin-right: 0.5rem;',
'  object-fit: cover;',
'}',
'',
'.name {',
'    font-family: Helvetica;',
'    font-weight: 400;',
'    font-size: 14px;',
'    line-height: 150%;',
'    letter-spacing: 0%;',
'    vertical-align: middle;',
'    text-transform: capitalize;',
'    color: #423B3B;',
'}',
'',
'/* Responsive tweaks */',
'@media (max-width: 600px) {',
'  .description {',
'    font-size: 16px;;',
'  }',
'',
'  .name {',
'    font-size: 14px;',
'  }',
'',
'  .avatar {',
'    width: 1.75rem;',
'    height: 1.75rem;',
'  }',
'}',
'',
'ul{',
'    font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'text-transform: capitalize;',
'/* color: #7A7A7A; */',
'}',
'',
'.comp-desc{',
'        font-family: Helvetica;',
'font-weight: 400;',
'font-size: 16px;',
'line-height: 150%;',
'letter-spacing: 0%;',
'color: #7A7A7A;',
'}',
'',
'.showing{',
'  display: flex;',
'  gap: 24px;',
'  align-items: center;',
'  margin: 0 24px;',
'}',
'',
'ui-dialog-content ui-widget-content{',
'    padding: 25px;',
'}',
'',
'.a-AlertMessage{',
'    padding: 25px;',
'}',
'',
'.a-AlertMessage-icon{',
'    background-color: #D0E4FB;',
'     padding: 10px;',
'}',
'',
'.a-AlertMessage-title {',
'    font-family: Helvetica;',
'}',
'',
'.a-AlertMessage-details{',
'    font-family: Helvetica;',
'}',
'',
'js-confirmBtn ui-button ui-corner-all ui-widget ui-button--hot{',
'    font-family: Helvetica;',
'}',
'',
'/* Cancel button (optional separate styling) */',
'.ui-dialog.my-custom-class .ui-dialog-buttonpane .ui-button:contains("Cancel") {',
'  background-color: #e0e0e0;',
'  color: #333;',
'}',
'',
''))
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'25'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114371389708692060)
,p_plug_name=>'Company Setup'
,p_icon_css_classes=>'fa-address-book'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2674017834225413037
,p_plug_display_sequence=>20
,p_plug_display_point=>'REGION_POSITION_01'
,p_location=>null
,p_menu_id=>wwv_flow_imp.id(56394687327590424)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114371560586692061)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>3371237801798025892
,p_plug_display_sequence=>30
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'',
'BEGIN',
'  -- Fetch the companies from company table.',
' FOR i in (SELECT ',
'              company_id,',
'              company_name,',
'              company_desc,',
'              decode(company_status, ''A'', ''Active'', ''I'', ''Inactive'') status,',
'              img_url',
'             FROM XXMRKT.XXMRKT_COMPANY_LIST',
'             WHERE COMPANY_TYPE = ''Loan Services''',
'             AND COMPANY_cODE = :AP_COMPANY_CODE',
'             AND COMPANY_ID = :AP_COMPANY_ID',
'             ORDER BY 1',
') LOOP',
'  RETURN',
'        ''<div class="top-region-header">',
'                <div class = "internal-flex">',
'                    <div class="img-div">',
'                        <img class ="prod-img" src="https://testapp.softsuite.com/softsuite/api/mrkt/getimages/''||:AP_COMPANY_ID||''" alt="group">',
'                    </div>',
'                    <div class="text-set">',
'                        <p class="company_name">''||i.company_name||''</p>'';',
'                        if i.status = ''Active'' then',
'                            RETURN ''<span style="background:#ECFDF3">''||i.status||''</span>'';',
'                        else',
'                            RETURN ''<span>''||i.status||''</span>'';',
'                        end if;',
'             RETURN ''</div>',
'                </div>',
'          </div>    ',
'         '';',
'    END LOOP;',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114372475364692070)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:t-TabsRegion-mod--simple'
,p_plug_template=>3223171818405608528
,p_plug_display_sequence=>50
,p_location=>null
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114373378936692079)
,p_plug_name=>'New'
,p_region_template_options=>'#DEFAULT#:js-useLocalStorage:t-TabsRegion-mod--fillLabels:t-TabsRegion-mod--simple'
,p_plug_template=>3223171818405608528
,p_plug_display_sequence=>40
,p_location=>null
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(73392407907060003)
,p_plug_name=>'Users'
,p_parent_plug_id=>wwv_flow_imp.id(114373378936692079)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>40
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type    VARCHAR2(100);',
'    v_type         NUMBER; -- 1 is for loan services',
'    v_count        NUMBER;',
'    v_offset       NUMBER := NVL(:P2_USERS_OFFSET, 1);',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_USER_DATA'''''';',
'    v_item         VARCHAR2(100) := ''''''P2_USERS_OFFSET'''''';',
'    v_region         VARCHAR2(100) := ''''''users'''''';',
'    v_last_shown    NUMBER := 0;',
'BEGIN',
'    -- Get company type',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :AP_COMPANY_ID;',
'    EXCEPTION',
'        WHEN NO_DATA_FOUND THEN',
'            NULL;',
'    END;',
'',
'    -- Count users for pagination',
'    SELECT CEIL(COUNT(*) / v_page_size)',
'      INTO v_count',
'      FROM XXMRKT.XXMRKT_MARKETPLACE_USERS',
'     WHERE COMPANY_ID   = :P2_COMPANY_ID',
'       AND COMPANY_CODE = :AP_COMPANY_CODE',
'       AND COMPANY_TYPE = ''Loan Services''',
'       AND CATEGORY     = ''USER''',
'     ORDER BY CREATION_DATE DESC;',
'',
'    -- Render HTML if company type is Loan Services',
'    IF v_comp_type = ''Loan Services'' THEN',
'        v_type := 1;',
'',
'        IF v_offset < 1 THEN',
'            v_offset := 1;',
'        ELSIF v_offset > v_count THEN',
'            v_offset := v_count;',
'        END IF;',
'',
'        -- Begin HTML Output',
'        htp.p(''',
'              <div class="controls">',
'                <h2>Users</h2>',
'                <div>',
'                  <input type="text" id="users-search" placeholder="Search Users..." onkeyup="filterUsers()" class="search-input">',
'                  <button class="add-btn" onclick="return redirectToModalPageCreateProduct(7,'' || :P2_COMPANY_ID || '','' || v_type || '')">Add New User</button>',
'                </div>',
'              </div>',
'',
'              <div class="table-wrapper">',
'                <table>',
'                  <thead>',
'                    <tr>',
'                      <th>Username</th>',
'                      <th>Name</th>',
'                      <th>Email Address</th>',
'                      <th>Status</th>',
'                      <th>Action</th>',
'                    </tr>',
'                  </thead>',
'                  <tbody id="users-table-body">',
'                    <!-- Dynamic rows go here -->',
'                  </tbody>',
'                </table>',
'              </div>'');',
'',
'                    -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="users-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'              </div>',
'',
'              <div class="page-buttons">',
'                <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&lt;</button>'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                                                                            -- Show first, last, current, and one before/after current',
'                        IF i = 1 OR i = v_count OR i = v_offset OR i = v_offset - 1 OR i = v_offset + 1 THEN',
'                                  ',
'                                  -- If there is a gap between last shown and current, add ellipsis',
'                            IF v_last_shown <> 0 AND i > v_last_shown + 1 THEN',
'                                    htp.p(''<span class="pagination-ellipsis">...</span>'');',
'                            END IF;',
'',
'                                  -- Render button',
'                                  htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                                  v_last_shown := i;',
'',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&gt;</button>',
'            </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'',
'        RETURN NULL;',
'    END IF;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114373454376692080)
,p_plug_name=>'Description'
,p_parent_plug_id=>wwv_flow_imp.id(114373378936692079)
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4501440665235496320
,p_plug_display_sequence=>10
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_content clob;',
'    q_content clob;',
'    v_data clob;',
'begin',
'',
'    for i in (SELECT ',
'              company_id,',
'              company_name,',
'              company_desc,',
'              decode(company_status, ''A'', ''Active'', ''I'', ''Inactive'') status,',
'              img_url,',
'              benefits',
'             FROM XXMRKT.XXMRKT_COMPANY_LIST',
'             WHERE COMPANY_ID = :AP_COMPANY_ID',
'              and company_code = :AP_cOMPANY_cODE)',
'    loop',
'    ',
'        RETURN ''<div class = "container">',
'                    <button class="edit-button" onclick="return redirectToModalPageEditCompany(4,''||i.company_id||'')"> ',
'                      <img src="https://cdn.jsdelivr.net/npm/bootstrap-icons/icons/pencil.svg" alt="Edit Icon" class="icon">',
'                      Edit Company Info',
'                    </button>',
'                    <div class="product-description">',
'                        <p class="description-header">Description</p>',
'                        <p class="comp-desc">''||i.company_Desc||''</p>',
'                    </div>',
'                    <div class="product-description2">',
'                              <p class="description-header">Key Features</p>',
'                            ''||i.benefits||''',
'                    </div>',
'                </div>'';',
'     end loop;',
'    ',
'end;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114373575871692081)
,p_plug_name=>'Products'
,p_parent_plug_id=>wwv_flow_imp.id(114373378936692079)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>30
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type    VARCHAR2(100);',
'    v_type         NUMBER; -- 1 is for loan services',
'    v_count        NUMBER;',
'    v_offset       NUMBER;',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_DATA'''''';',
'    v_item         VARCHAR2(100) := ''''''P2_PROD_OFFSET'''''';',
'    v_region         VARCHAR2(100) := ''''''products'''''';',
'    v_last_shown NUMBER := 0;',
'BEGIN',
'',
'    BEGIN',
'        v_offset := TO_NUMBER(:P2_PROD_OFFSET);',
'    EXCEPTION',
'        WHEN VALUE_ERROR THEN',
'            v_offset := 1;',
'    END;',
'    -- Get company type',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :AP_COMPANY_ID;',
'    EXCEPTION',
'        WHEN NO_DATA_FOUND THEN',
'            NULL;',
'    END;',
'',
'    -- Count users for pagination',
'    SELECT CEIL(COUNT(*) / v_page_size)',
'      INTO v_count',
'    FROM XXMRKT.XXMRKT_PRODUCT_LIST A, ',
'      --  XXHRMS.XXHRMS_ELEMENTS B, ',
'        XXMRKT.XXMRKT_LOAN_TYPES C,',
'        XXMRKT.XXMRKT_COMPANY_LIST D',
'    WHERE A.COMPANY_ID = :AP_COMPANY_ID',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'  --  AND A.DEDUCTION_HEADER = B.ELEMENT_ID',
'    AND A.COMPANY_ID = D.COMPANY_ID',
'    AND to_Char(A.PRODUCT_TYPE) = to_char(C.LOAN_TYPE_ID)',
'    AND D.COMPANY_TYPE = ''Loan Services''',
'    ORDER BY A.CREATION_DATE DESC;',
'',
'    -- Render HTML if company type is Loan Services',
'    IF v_comp_type = ''Loan Services'' THEN',
'        v_type := 1;',
'',
'        IF v_offset < 1 THEN',
'            v_offset := 1;',
'        ELSIF v_offset > v_count THEN',
'            v_offset := v_count;',
'        END IF;',
'                        -- Begin HTML Output',
'        htp.p(''',
'              <div class="controls">',
'				<h2>Products</h2>',
'				<div>',
'				<input type="text" id="product-search" placeholder="Search products..." onkeyup="filterProducts()" class="search-input">',
'					<button class="add-btn" onclick="return redirectToModalPageCreateProduct(8,''||:AP_COMPANY_ID||'',''||v_type||'')">Add New Product</button>',
'',
'				</div>',
'			  </div>',
'',
'			  <div class="table-wrapper">',
'				<table>',
'				  <thead>',
'					<tr>',
'					  <th>Product Name</th>',
'					  <th>Product Type</th>',
'					  <th>Interest Rate %</th>',
'					  <th>Minimum Limit</th>',
'					  <th>Maximum Limit</th>',
'					  <th>Min Repayment Period (Months)</th>',
'					  <th>Max Repayment Period (Months)</th>',
'					  <th>Charges</th>',
'					  <th>Insurance Fees</th>',
'					  <th>Status</th>',
'					  <th>Action</th>',
'					</tr>',
'				  </thead>',
'				  <tbody id="product-table-body">',
'					<!-- Dynamic rows go here -->',
'				  </tbody>',
'				</table>',
'			  </div>'');',
'                    -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="products-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'','' || v_count || '')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                        <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'                      </div>',
'',
'                      <div class="page-buttons">',
'                        <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '','' || v_count || '')">&lt;</button>'');',
'',
'                            FOR i IN 1..v_count LOOP',
'                                                                            -- Show first, last, current, and one before/after current',
'                                IF i = 1 OR i = v_count OR i = v_offset OR i = v_offset - 1 OR i = v_offset + 1 THEN',
'                                  ',
'                                  -- If there is a gap between last shown and current, add ellipsis',
'                                  IF v_last_shown <> 0 AND i > v_last_shown + 1 THEN',
'                                    htp.p(''<span class="pagination-ellipsis">...</span>'');',
'                                  END IF;',
'',
'                                  -- Render button',
'                                  htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                                  v_last_shown := i;',
'',
'                                END IF;',
'                            END LOOP;',
'',
'                            htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '','' || v_count || '')">&gt;</button>',
'                    </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'',
'        RETURN NULL;',
'    END IF;',
'EXCEPTION',
'    WHEN OTHERS THEN ',
'         null;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(114373690480692083)
,p_plug_name=>'Ratings and Recommendations'
,p_parent_plug_id=>wwv_flow_imp.id(114373378936692079)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>70
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'',
'BEGIN',
'htp.p(''<div class="review-section id="rating">',
'            <div onclick="return" class="review-header">',
'            <h3>Reviews/Recommendations</h3>',
'          </div>'');',
'        FOR i IN (select review_id,',
'                         decode(rating, 5, ''Excellent'', 4, ''Very Good'', 3, ''Average'', 2, ''Poor'', 1, ''Bad/ Avoid Product'', 0, ''Not Rated'') rating,',
'                         comments,',
'                         reviewer_name,',
'                         reviewer_id',
'                    from XXMRKT.XXMRKT_PRODUCT_REVIEWS',
'                    where COMPANY_ID = :AP_COMPANY_ID',
'                    and COMPANY_CODE = :AP_COMPANY_CODE',
'                  ) ',
'        LOOP',
'        htp.p( ',
'        ''',
'          <div class="review-box">',
'             <div class="review-title">',
'                <strong>Product Rating - ''||i.rating||''</strong>',
'            </div>',
'            <p>',
'              ''||i.comments||''',
'            </p>',
'            ',
'            <div class="reviewer">',
'              <img src="https://testapp.softsuite.com/softsuite/api/mrkt/getreviewerimage/''||i.reviewer_id||''" alt="Reviewer Photo" class="reviewer-photo">',
'              <span class="reviewer-name">''||i.reviewer_name||''</span>',
'            </div>',
'          </div>''',
'        );',
'    END LOOP;',
' htp.p(''</div>',
'',
''');',
'END;'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(137375311427469161)
,p_plug_name=>'Approvers'
,p_parent_plug_id=>wwv_flow_imp.id(114373378936692079)
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>50
,p_plug_display_point=>'SUB_REGIONS'
,p_location=>null
,p_function_body_language=>'PLSQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_comp_type    VARCHAR2(100);',
'    v_type         NUMBER; -- 1 is for loan services',
'    v_count        NUMBER;',
'    v_offset       NUMBER := NVL(:P2_APPR_OFFSET, 1);',
'    v_page_size    NUMBER := 5;',
'    v_process      VARCHAR2(200) := ''''''GET_APPROVERS_DATA'''''';',
'    v_item         VARCHAR2(100) := ''''''P2_APPR_OFFSET'''''';',
'    v_region         VARCHAR2(100) := ''''''approvers'''''';',
'    v_last_shown    NUMBER := 0;',
'BEGIN',
'    -- Get company type',
'    BEGIN',
'        SELECT COMPANY_TYPE',
'          INTO v_comp_type',
'          FROM XXMRKT.XXMRKT_COMPANY_LIST',
'         WHERE COMPANY_ID = :AP_COMPANY_ID;',
'    EXCEPTION',
'        WHEN NO_DATA_FOUND THEN',
'            NULL;',
'    END;',
'',
'    -- Count approvers for pagination',
'    SELECT CEIL(COUNT(*) / v_page_size)',
'      INTO v_count',
'    FROM XXMRKT.XXMRKT_APPROVAL_SETUP A, XXMRKT.XXMRKT_MARKETPLACE_USERS B',
'    WHERE A.COMPANY_ID = :AP_COMPANY_ID',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'    AND A.USERNAME = B.USER_ID',
'    AND B.CATEGORY = ''USER''',
'   -- AND COMPANY_TYPE = ''Loan Services''',
'    ORDER BY A.approval_level DESC;',
'',
'    -- Render HTML if company type is Loan Services',
'    IF v_comp_type = ''Loan Services'' THEN',
'        v_type := 1;',
'',
'        IF v_offset < 1 THEN',
'            v_offset := 1;',
'        ELSIF v_offset > v_count THEN',
'            v_offset := v_count;',
'        END IF;',
'',
'        -- Begin HTML Output',
'        htp.p(''',
'                <div class="controls">',
'				<h2>Approvers</h2>',
'				<div>',
'				<input type="text" id="approvers-search" placeholder="Search Approvers..." onkeyup="filterApprovers()" class="search-input">',
'				<button class="add-btn" onclick="return redirectToModalPageCreateApprovers(5,''||:AP_COMPANY_ID||'',''||v_type||'')">Add New Approver</button>',
'				</div>',
'			  </div>',
'',
'			  <div class="table-wrapper">',
'				<table>',
'				  <thead>',
'					<tr>',
'					  <th>Username</th>  ',
'					  <th>Name</th>',
'					  <th>Email Address</th>',
'					  <th>Approval Level</th>',
'					  <th>Status</th>',
'					  <th>Action</th>',
'					</tr>',
'				  </thead>',
'				  <tbody id="approvers-table-body">',
'					<!-- Dynamic rows go here -->',
'				  </tbody>',
'				</table>',
'			  </div>'');',
'',
'                    -- Pagination Controls',
'                    htp.p(''<div class="pagination">',
'              <div class="showing">',
'                <span>Showing</span>',
'                <select id="approvers-select" onchange="handlePageChange(this,''|| v_process || '', '' || v_item || '', ''||v_region||'')">'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                        IF i = v_offset THEN',
'                            htp.p(''<option value="'' || i || ''" selected>'' || i || ''</option>'');',
'                        ELSE',
'                            htp.p(''<option value="'' || i || ''">'' || i || ''</option>'');',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''</select>',
'                <span>out of <span id="total-pages">'' || v_count || ''</span></span>',
'              </div>',
'',
'              <div class="page-buttons">',
'                <button id="prev" onclick="return apprPaginate(-1,'' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&lt;</button>'');',
'',
'                    FOR i IN 1..v_count LOOP',
'                                                                            -- Show first, last, current, and one before/after current',
'                        IF i = 1 OR i = v_count OR i = v_offset OR i = v_offset - 1 OR i = v_offset + 1 THEN',
'                                  ',
'                                  -- If there is a gap between last shown and current, add ellipsis',
'                            IF v_last_shown <> 0 AND i > v_last_shown + 1 THEN',
'                                    htp.p(''<span class="pagination-ellipsis">...</span>'');',
'                            END IF;',
'',
'                                  -- Render button',
'                                  htp.p(''<button onclick="return getData('' || i || '', '' || v_process || '', '' || v_region || '')">'' || i || ''</button>'');',
'                                  v_last_shown := i;',
'',
'                        END IF;',
'                    END LOOP;',
'',
'                    htp.p(''<button onclick="return apprPaginate(1, '' || v_process || '', '' || v_item || '', '' || v_region || '', '' || v_count || '')">&gt;</button>',
'            </div>'');',
'',
'                    -- Close Wrapper',
'                    htp.p(''</div>',
'            '');',
'',
'        RETURN NULL;',
'    END IF;',
'END;',
''))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_DYNAMIC_CONTENT'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75566676390060735)
,p_name=>'P2_USERS_OFFSET'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(114372475364692070)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75566887514060737)
,p_name=>'P2_PROD_OFFSET'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(114372475364692070)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(75566903706060738)
,p_name=>'P2_APPR_OFFSET'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(114372475364692070)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(114376197627692192)
,p_name=>'P2_COMPANY_ID'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(114372475364692070)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(70371524813679395)
,p_name=>'New'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'ready'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(70372094851679402)
,p_event_id=>wwv_flow_imp.id(70371524813679395)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'apex.util.getTopApex().jQuery(".modal-dialog--pullout .ui-dialog-title").prepend(''<img src="#APP_IMAGES#Featured icon.png" style="height:48px;"/>'');'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(67799522951363243)
,p_process_sequence=>10
,p_process_point=>'BEFORE_HEADER'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'New'
,p_process_sql_clob=>':P2_COMPANY_ID := :AP_COMPANY_ID;'
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>67799522951363243
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(70370748885679380)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'      v_page_size number := 5;',
'BEGIN',
'   :P2_PROD_OFFSET := apex_application.g_x02;',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'    SELECT product_id,',
'           A.company_id,',
'           product_name,',
'           c.loan_type product_type,',
'           interest_rate,',
'       --    b.name deduction_header,',
'           to_char(nvl(minimum_limit,0), ''999G999G999G999G990D00'') minimum_limit,',
'           to_char(nvl(maximum_limit, 0), ''999G999G999G999G990D00'') maximum_limit,',
'           minimum_repayment_period,',
'           maximum_repayment_period,',
unistr('           decode(charges_type, ''Percentage'', ''%'', ''Amount'', ''\20A6'') charges_type,'),
'           nvl(charges, 0) charges,',
unistr('           decode(insfees_type, ''Percentage'', ''%'', ''Amount'', ''\20A6'') insfees_type,'),
'           nvl(insurance_fee, 0) insurance_fee,',
'           decode(A.status, ''A'', ''Active'', ''I'', ''Inactive'') status',
'    FROM XXMRKT.XXMRKT_PRODUCT_LIST A, ',
'      --  XXHRMS.XXHRMS_ELEMENTS B, ',
'        XXMRKT.XXMRKT_LOAN_TYPES C,',
'        XXMRKT.XXMRKT_COMPANY_LIST D',
'    WHERE A.COMPANY_ID = :AP_COMPANY_ID',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'  --  AND A.DEDUCTION_HEADER = B.ELEMENT_ID',
'    AND A.COMPANY_ID = D.COMPANY_ID',
'    AND to_Char(A.PRODUCT_TYPE) = to_char(C.LOAN_TYPE_ID)',
'    AND D.COMPANY_TYPE = ''Loan Services''',
'    ORDER BY A.CREATION_DATE DESC',
'   -- OFFSET nvl(apex_application.g_x02, 1) - 1  ROWS',
'    --FETCH NEXT v_page_size ROWS ONLY',
'  )',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''productID'', pro_rec.product_id);',
'    apex_json.write(''companyID'', pro_rec.company_id);',
'    apex_json.write(''productName'', pro_rec.product_name);',
'    apex_json.write(''productType'', pro_rec.product_type);',
'    apex_json.write(''interestRate'', pro_rec.interest_rate);',
'    apex_json.write(''minimumLimits'', pro_rec.minimum_limit);',
'    apex_json.write(''maximumLimits'', pro_rec.maximum_limit);',
'    apex_json.write(''minimumRepaymentPeriod'', pro_rec.minimum_repayment_period);',
'    apex_json.write(''maximumRepaymentPeriod'', pro_rec.maximum_repayment_period);',
'  --  apex_json.write(''deductionHeader'', pro_rec.deduction_header);',
'    apex_json.write(''chargesType'', pro_rec.charges_type);',
'    apex_json.write(''charges'', pro_rec.charges);',
'    apex_json.write(''insuranceFeesType'', pro_rec.insfees_type);',
'    apex_json.write(''insuranceFees'', pro_rec.insurance_fee);',
'    apex_json.write(''status'', pro_rec.status);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>70370748885679380
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(70371182293679394)
,p_process_sequence=>20
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_APPROVERS_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'  :P2_APPR_OFFSET := apex_application.g_x02;',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'    SELECT id,',
'           a.company_id,',
'           b.user_name,',
'           a.email_Address,',
'           full_name,',
'           a.approval_level,',
'           decode(a.status, ''A'', ''Enabled'', ''I'', ''Disabled'') status',
'    FROM XXMRKT.XXMRKT_APPROVAL_SETUP A, XXMRKT.XXMRKT_MARKETPLACE_USERS B',
'    WHERE A.COMPANY_ID = :P2_COMPANY_ID',
'    AND A.COMPANY_CODE = :AP_COMPANY_CODE',
'    AND A.USERNAME = B.USER_ID',
'    AND B.CATEGORY = ''USER''',
'   -- AND COMPANY_TYPE = ''Loan Services''',
'    ORDER BY A.approval_level ASC',
'  )',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''Id'', pro_rec.id);',
'    apex_json.write(''companyID'', pro_rec.company_id);',
'    apex_json.write(''userName'', pro_rec.user_name);',
'    apex_json.write(''emailAddress'', pro_rec.email_Address);',
'    apex_json.write(''approvalLevel'', pro_rec.approval_level);',
'    apex_json.write(''fullName'', pro_rec.full_name);',
'    apex_json.write(''status'', pro_rec.status);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>70371182293679394
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(73392671373060005)
,p_process_sequence=>30
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GET_USER_DATA'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_page_size number := 5;',
'BEGIN',
'  :P2_USERS_OFFSET := apex_application.g_x02;',
'  -- Open JSON array',
'  apex_json.open_array;',
'',
'  FOR pro_rec IN (',
'    SELECT user_id,',
'           company_id,',
'           user_name,',
'           full_name,',
'           email_Address,',
'           decode(status, ''A'', ''Enabled'', ''I'', ''Disabled'') status',
'    FROM XXMRKT.XXMRKT_MARKETPLACE_USERS',
'    WHERE COMPANY_ID = :P2_COMPANY_ID',
'    AND COMPANY_CODE = :AP_COMPANY_CODE',
'    AND COMPANY_TYPE = ''Loan Services''',
'    AND CATEGORY = ''USER''',
'    ORDER BY CREATION_DATE DESC',
'    --OFFSET apex_application.g_x02 - 1  ROWS',
'   -- FETCH NEXT v_page_size ROWS ONLY',
'  )',
'  LOOP',
'    apex_json.open_object;',
'    apex_json.write(''userId'', pro_rec.user_id);',
'    apex_json.write(''companyID'', pro_rec.company_id);',
'    apex_json.write(''userName'', pro_rec.user_name);',
'    apex_json.write(''emailAddress'', pro_rec.email_Address);',
'    apex_json.write(''fullName'', pro_rec.full_name);',
'    apex_json.write(''status'', pro_rec.status);',
'    apex_json.close_object;',
'  END LOOP;',
'',
'  apex_json.close_array;',
'',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    -- Clear previous output (if any)',
'    apex_json.free_output;',
'    ',
'    -- Start fresh JSON error response',
'    apex_json.open_object;',
'    apex_json.write(''status'', ''error'');',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'',
'    -- RAISE_APPLICATION_ERROR is optional here; use it to signal error to JavaScript',
'    -- raise_application_error(-20001, SQLERRM);',
'END;',
'',
'',
''))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>73392671373060005
);
wwv_flow_imp.component_end;
end;
/
